version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mockitupai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mockitupai
    restart: unless-stopped

volumes:
  mongodb_data:
